In [8]:
import numpy as np

In [10]:
arr  = np.arange(10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.random.randn(10,3)

array([[ 0.29583956,  2.0743947 ,  0.68883234],
       [ 0.67221641, -0.73856483, -1.78844628],
       [ 0.22614279, -0.09082702,  0.76168662],
       [ 1.11664101, -0.86245184,  0.9734642 ],
       [ 0.81746039,  0.52978504, -0.93200663],
       [-0.32355725,  1.3647097 ,  0.53018959],
       [ 0.63623495, -0.58687705,  0.93940706],
       [-0.05268748,  0.34064804, -1.1223772 ],
       [-0.11338372, -1.53084996,  0.64117323],
       [-1.36591705, -0.22988468, -1.34407512]])

### Reshaping

In [27]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = arr.reshape((2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Transposing

In [34]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### Np.meshgrid

In [36]:
points = np.arange(-5, 5, 0.01)

In [37]:
xs, ys = np.meshgrid(points, points)

In [38]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]],
      shape=(1000, 1000))

### Expressing Conditional and Logic Operations with Numpy



In [49]:
xarr = np.arange(1.1,1.6,0.1)
yarr = np.arange(2.1, 2.6, 0.1)
xarr, yarr

(array([1.1, 1.2, 1.3, 1.4, 1.5]), array([2.1, 2.2, 2.3, 2.4, 2.5]))

In [50]:
cond = np.array([True, False, True, False, False])
cond

array([ True, False,  True, False, False])

Let's say we want to take a value from `xarr` when cond[i] is True and a value from `yarr` when cond[i] is False we can use `np.where`:

(The second and third arguments don't have to be an array, the first one can be a condition)

In [51]:
result = np.where(cond, xarr, yarr)

In [52]:
result

array([1.1, 2.2, 1.3, 2.4, 2.5])

In [53]:
arr = np.random.randn(4,4)
arr

array([[ 0.09680969, -0.28676487,  1.34648161, -0.62756455],
       [ 1.33915764, -0.76269956,  0.84669775, -0.1477824 ],
       [-0.12167134,  1.74031397,  1.31161248,  0.7884128 ],
       [ 0.99858913, -0.30281798,  1.3155949 ,  0.66766742]])

In [55]:
np.where(arr>0, 2, arr)

array([[ 2.        , -0.28676487,  2.        , -0.62756455],
       [ 2.        , -0.76269956,  2.        , -0.1477824 ],
       [-0.12167134,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.30281798,  2.        ,  2.        ]])