In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

2.6.0+cu118


# Introduction 

### Creating Tensors

In [3]:
# scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.dtype

torch.int64

In [6]:
scalar.ndim

0

In [7]:
# Get tensor value back
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7,7])

In [9]:
vector

tensor([7, 7, 7])

In [10]:
vector.dtype

torch.int64

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([3])

In [13]:
# MATRIX
matrix = torch.tensor([[7,8], [2,3]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
matrix[1]

tensor([2, 3])

In [17]:
matrix[1][1]

tensor(3)

In [18]:
# Tensor
TENSOR = torch.tensor([[[0.1,2,3],[4,5,6], [7,8,9]], [[1,3,4], [1,5,6], [1,4,3]]])

In [19]:
TENSOR

tensor([[[0.1000, 2.0000, 3.0000],
         [4.0000, 5.0000, 6.0000],
         [7.0000, 8.0000, 9.0000]],

        [[1.0000, 3.0000, 4.0000],
         [1.0000, 5.0000, 6.0000],
         [1.0000, 4.0000, 3.0000]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([2, 3, 3])

In [22]:
TENSOR.dtype

torch.float32

## Random Tensors:

Why random tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust to random numbers

`Start with Random Numbers` -> `look at data` -> `update random numbers` -> `look at data` -> `update random numbers`

https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(1 ,10, 10)

In [24]:
random_tensor

tensor([[[0.6568, 0.0136, 0.8032, 0.1384, 0.6687, 0.2018, 0.4297, 0.9056,
          0.8508, 0.0558],
         [0.5176, 0.1405, 0.8899, 0.5471, 0.9527, 0.2354, 0.3116, 0.4450,
          0.4319, 0.3050],
         [0.2239, 0.9280, 0.3444, 0.0083, 0.0373, 0.8639, 0.7611, 0.8091,
          0.7374, 0.2115],
         [0.9671, 0.2753, 0.5928, 0.7696, 0.9150, 0.9360, 0.4025, 0.9261,
          0.3665, 0.8420],
         [0.3097, 0.7043, 0.1591, 0.1050, 0.9369, 0.1520, 0.6709, 0.0415,
          0.5848, 0.4323],
         [0.1170, 0.2894, 0.4067, 0.0646, 0.3964, 0.3267, 0.2128, 0.4770,
          0.8787, 0.9020],
         [0.5842, 0.0410, 0.0720, 0.9427, 0.0303, 0.7480, 0.1827, 0.0319,
          0.7127, 0.0152],
         [0.8769, 0.7629, 0.2868, 0.2077, 0.3233, 0.0594, 0.2758, 0.3606,
          0.7796, 0.7831],
         [0.7882, 0.5605, 0.3880, 0.1482, 0.6817, 0.5181, 0.7943, 0.7301,
          0.6237, 0.6444],
         [0.7200, 0.9480, 0.1834, 0.1709, 0.6476, 0.1653, 0.1322, 0.2977,
          0.1391,

In [25]:
random_tensor.shape

torch.Size([1, 10, 10])

In [26]:
random_tensor.ndim

3

In [27]:
# Create a random tensor with similar shape to an image
image_size_tensor = torch.rand(64, 64, 3) # RGB

In [28]:
image_size_tensor.shape

torch.Size([64, 64, 3])

In [29]:
image_size_tensor.ndim

3

### Manipulating Tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [30]:
# Create tensors
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 2

tensor([2, 4, 6])

In [32]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [33]:
tensor - 10

tensor([-9, -8, -7])

In [34]:
torch.mul(tensor, 3)

tensor([3, 6, 9])

In [35]:
torch.add(tensor , 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element Wise
2. Matrix Multiplication

In [36]:
TENSOR = torch.tensor([[[0.1,2,3],[4,5,6], [7,8,9]], [[1,3,4], [1,5,6], [1,4,3]]])
(TENSOR * TENSOR)

tensor([[[1.0000e-02, 4.0000e+00, 9.0000e+00],
         [1.6000e+01, 2.5000e+01, 3.6000e+01],
         [4.9000e+01, 6.4000e+01, 8.1000e+01]],

        [[1.0000e+00, 9.0000e+00, 1.6000e+01],
         [1.0000e+00, 2.5000e+01, 3.6000e+01],
         [1.0000e+00, 1.6000e+01, 9.0000e+00]]])

In [37]:
torch.matmul(TENSOR, TENSOR)

tensor([[[ 29.0100,  34.2000,  39.3000],
         [ 62.4000,  81.0000,  96.0000],
         [ 95.7000, 126.0000, 150.0000]],

        [[  8.0000,  34.0000,  34.0000],
         [ 12.0000,  52.0000,  52.0000],
         [  8.0000,  35.0000,  37.0000]]])

In [38]:
torch.rand(1, 10)

tensor([[0.7324, 0.5939, 0.1555, 0.2252, 0.3676, 0.4571, 0.6417, 0.5844, 0.4028,
         0.3900]])

In [39]:
torch.sum(torch.matmul(TENSOR, TENSOR))

tensor(985.6100)

In [40]:
x= torch.arange(0, 10, dtype = float)

In [41]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [42]:
torch.mean(x)

tensor(4.5000, dtype=torch.float64)

## Reshaping, Stacking, Squeezing, Unsqueezing 

* Reshaping: Reshapes a defined input tensor to a defined shape.
* View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: Removes all `1` dimension to a target tensor.
* Unsqueeze: Add a `1` dimension to a target tensor.
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way.

In [44]:
import torch

In [63]:
x = torch.arange(1, 11, dtype = float)

In [64]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [65]:
x.shape

torch.Size([10])

In [70]:
x_reshaped = x.reshape(5, 2)

In [71]:
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]], dtype=torch.float64)

In [72]:
z = x.view(2#, 5)
z

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=torch.float64)

# Changing z changes x because view of a tensor shares the same memory as the original input

In [74]:
z[:, 0] = 5

In [75]:
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]], dtype=torch.float64),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [98]:
# Stack Tensors on top 
x_stacked = torch.stack([z,z,z,z,z], dim = 1)
x_stacked

tensor([[[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  2.,  3.,  4.,  5.]],

        [[ 5.,  7.,  8.,  9., 10.],
         [ 5.,  7.,  8.,  9., 10.],
         [ 5.,  7.,  8.,  9., 10.],
         [ 5.,  7.,  8.,  9., 10.],
         [ 5.,  7.,  8.,  9., 10.]]], dtype=torch.float64)

In [104]:
torch.squeeze(z)

tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 5.,  7.,  8.,  9., 10.]], dtype=torch.float64)

In [105]:
z

tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 5.,  7.,  8.,  9., 10.]], dtype=torch.float64)

In [107]:
x = torch.zeros(2,1,2,1,2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [108]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [112]:
y = torch.squeeze(x)

In [113]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [114]:
y.squeeze()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [116]:
# Unsqueeze
torch.unsqueeze(x_reshaped, 0)

tensor([[[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  5.],
         [ 7.,  8.],
         [ 9., 10.]]], dtype=torch.float64)

In [119]:
x_reshaped

tensor([[ 5.,  2.],
        [ 3.,  4.],
        [ 5.,  5.],
        [ 7.,  8.],
        [ 9., 10.]], dtype=torch.float64)

In [120]:
x_reshaped.argmax()

tensor(9)

# Pytorch and Numpy:

In [124]:
import torch
import numpy
array = np.arange(0 ,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
x = torch.from_numpy(array)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
!nvidia-smi

Fri May  9 15:49:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.61                 Driver Version: 572.61         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0             16W /   50W |      77MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [128]:
torch.cuda.is_available()

True

In [129]:
device = 'cuda' if torch.cuda.is_available() else "cpu"

In [130]:
device

'cuda'